### ISSUE TITLE
Input files to repeat the experiments of Contention at CMT in the FAST 2018 paper.

### ISSUE THREAD

**Issue by zy-tough** [CMU-SAFARI/MQSim#12]
I cannot find the input files to repeat the experiments of Contention at the Cached Mapping Table (Section 6.1.3) in the FAST 2018 paper. Could you please provide the configuration files in this repository?

I am a little confused about how to set the execution time of the random access pattern and sequential access pattern in one run. 

In addition, could you please explain a little about the MIXED_STREAMING_RANDOM option in the IO flow configuration Address_Distribution?

**Comment by arashta** [comment]
The core message generator class has been modified according to our latest plan for synthetic message generation. The MIXED_STREAMING_RANDOM generation option is not working due to the mentioned changes and requires modification. We are now reimplementing this option and will include it in a future commit.
